name: advance-e2e-suite

on:
  pull_request:
    types: [labeled]

jobs:
  e2e-before-merge:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.names, 'ready-for-merge') }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install ginkgo
      run: go get github.com/onsi/ginkgo/ginkgo@v1.16.5

    - name: turn off swap
      run: sudo swapoff -a

    - name: Set netfilter conntrack max
      run: sudo sysctl -w net.netfilter.nf_conntrack_max=131072

    - name: Run Before-PR-Merging e2e tests
      run: yes | GINKGO_FOCUS="\[Before-PR-Merging\]" make test-e2e
