name: e2e-suite

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e-pr-blocking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install ginkgo
      run: go get github.com/onsi/ginkgo/ginkgo@v1.16.5

    - name: turn off swap
      run: sudo swapoff -a

    - name: Set netfilter conntrack max
      run: sudo sysctl -w net.netfilter.nf_conntrack_max=131072

    - name: Run cluster-class e2e tests
      run: |
        sed -i 's/e2e\/cluster-template.yaml/e2e\/topology\/cluster-template.yaml/' test/e2e/config/provider.yaml
        yes | GINGO_FOCUS="\[Cluster-Class\]" make test-e2e
